/**
 * SmartPage fingerprint — embedded in all HTML output so we can detect
 * whether content was generated by SmartPage or imported from elsewhere.
 * Uses a hidden data attribute on the root element, invisible in the UI.
 */
export const SMARTPAGE_FINGERPRINT = 'data-smartpage-origin="true"'

/** Check if HTML content contains the SmartPage fingerprint. */
export function hasSmartPageFingerprint(html: string): boolean {
  if (!html || html.trim().length === 0) return true // empty content is fine
  // Minimal content (just empty tags like <p></p>) is treated as fresh — no warning needed
  const textContent = html.replace(/<[^>]*>/g, '').trim()
  if (textContent.length === 0) return true // only empty tags, no real content
  return html.includes('data-smartpage-origin')
}

/**
 * Content styles shared between PDF export and preview.
 * These are the actual formatting styles that make the content
 * look correct — typography, tables, lists, code blocks, etc.
 * No page layout, no visual chrome.
 */
const CONTENT_STYLES = `
    h1 { font-size: 24pt; font-weight: 700; line-height: 1.2; margin: 0.5em 0 0.3em; }
    h2 { font-size: 18pt; font-weight: 600; line-height: 1.25; margin: 0.4em 0 0.25em; }
    h3 { font-size: 14pt; font-weight: 600; line-height: 1.3; margin: 0.35em 0 0.2em; }
    h4 { font-size: 12pt; font-weight: 600; line-height: 1.35; margin: 0.3em 0 0.15em; }
    p { margin: 0.25em 0; }

    ul, ol { padding-left: 1.5em; margin: 0.5em 0; }
    ul { list-style-type: disc; }
    ol { list-style-type: decimal; }
    li { margin: 0.15em 0; }

    ul[data-type="taskList"] { list-style: none; padding-left: 0; }
    ul[data-type="taskList"] li { display: flex; align-items: flex-start; gap: 0.5em; }

    blockquote {
      border-left: 3px solid #d1d5db;
      padding-left: 1em;
      margin: 0.5em 0;
      color: #6b7280;
    }

    code {
      background: #f3f4f6;
      border-radius: 3px;
      padding: 0.15em 0.3em;
      font-size: 0.9em;
      font-family: 'Courier New', monospace;
    }

    pre {
      background: #1e1e1e;
      border-radius: 6px;
      padding: 1em;
      margin: 0.5em 0;
      overflow-x: auto;
    }

    pre code {
      background: none;
      padding: 0;
      color: #d4d4d4;
    }

    table {
      border-collapse: collapse;
      width: 100%;
      margin: 0.5em 0;
    }

    td, th {
      border: 1px solid #d1d5db;
      padding: 8px 12px;
      vertical-align: top;
    }

    th {
      background: #f9fafb;
      font-weight: 600;
    }

    /* Borderless tables */
    table[data-border-style="none"] td,
    table[data-border-style="none"] th {
      border-color: transparent;
    }

    table[data-border-style="none"] th {
      background: transparent;
      text-align: left;
    }

    img {
      max-width: 100%;
      height: auto;
    }

    .image-container { margin: 0.5em 0; }

    a {
      color: #2563eb;
      text-decoration: underline;
    }

    hr {
      border: none;
      border-top: 1px solid #e5e7eb;
      margin: 1.5em 0;
    }

    mark {
      background-color: #fef08a;
      padding: 0.1em 0;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .text-left, [style*="text-align: left"] { text-align: left; }
    .text-center, [style*="text-align: center"] { text-align: center; }
    .text-right, [style*="text-align: right"] { text-align: right; }
    .text-justify, [style*="text-align: justify"] { text-align: justify; }

    /* Template variables */
    .template-variable, span[data-variable] {
      display: inline;
      background: #ede9fe;
      color: #6d28d9;
      border: 1px solid #c4b5fd;
      border-radius: 4px;
      padding: 0 4px;
      font-size: 0.85em;
      font-family: 'Courier New', monospace;
      white-space: nowrap;
    }
`

interface ExportOptions {
  title?: string
  pageSize?: 'A4' | 'Letter'
  margins?: { top: string; right: string; bottom: string; left: string }
  extraStyles?: string
  header?: string
  footer?: string
}

/**
 * Export editor content as clean HTML for PDF generation.
 *
 * This produces a self-contained HTML document with:
 * - @page rules for PDF library page sizing/margins
 * - Content formatting styles (typography, tables, lists, code, images, etc.)
 * - Page break markers converted to CSS page-break-after
 * - NO page wrappers, NO shadows, NO gray background, NO pagination script
 *
 * Pass this HTML to any PDF library (Puppeteer, wkhtmltopdf, Prince, etc.)
 * and the library handles page layout automatically using the @page rules.
 */
export function exportToPdfHtml(editorHtml: string, options: ExportOptions = {}): string {
  const {
    title = 'Document',
    pageSize = 'A4',
    margins = { top: '25.4mm', right: '25.4mm', bottom: '25.4mm', left: '25.4mm' },
    extraStyles = '',
    header = '',
    footer = '',
  } = options

  // Strip page break divs and replace with CSS page-break markers
  const cleanedHtml = editorHtml.replace(
    /<div[^>]*data-page-break[^>]*><\/div>/gi,
    '<div style="page-break-after: always; break-after: page;"></div>'
  )

  // For print: use a table-based layout to repeat header/footer on every page.
  // This is the most reliable cross-browser approach for repeating page headers.
  // <thead> repeats at the top of every page, <tfoot> at the bottom.
  const safeHeader = sanitizeHtml(header)
  const safeFooter = sanitizeHtml(footer)
  const hasHeader = safeHeader && safeHeader !== '<p></p>'
  const hasFooter = safeFooter && safeFooter !== '<p></p>'

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    @page {
      size: ${pageSize};
      margin: ${hasHeader ? '10mm' : margins.top} ${margins.right} ${hasFooter ? '10mm' : margins.bottom} ${margins.left};
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.5;
      color: #1a1a1a;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    ${CONTENT_STYLES}
    ${extraStyles}

    /* Table-based layout for repeating header/footer on every printed page */
    .doc-table {
      width: 100%;
      border-collapse: collapse;
    }
    .doc-table > thead > tr > th,
    .doc-table > tbody > tr > td,
    .doc-table > tfoot > tr > td {
      border: none !important;
      padding: 0;
      vertical-align: top;
    }

    .doc-header {
      padding: 0;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .doc-header-content {
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
      margin-bottom: 8px;
    }
    .doc-header img {
      max-width: 100%;
      height: auto;
      display: block;
    }
    .doc-header p { margin: 0; }

    .doc-footer {
      padding: 0;
    }
    .doc-footer-content {
      padding-top: 8px;
      border-top: 1px solid #e5e7eb;
      margin-top: 8px;
    }
    .doc-footer img {
      max-width: 100%;
      height: auto;
      display: block;
    }
    .doc-footer p { margin: 0; }
  </style>
</head>
<body>
  <table class="doc-table">
    ${hasHeader ? `<thead><tr><td class="doc-header"><div class="doc-header-content">${safeHeader}</div></td></tr></thead>` : ''}
    ${hasFooter ? `<tfoot><tr><td class="doc-footer"><div class="doc-footer-content">${safeFooter}</div></td></tr></tfoot>` : ''}
    <tbody><tr><td class="doc-body">
      ${cleanedHtml}
    </td></tr></tbody>
  </table>
</body>
</html>`
}

/**
 * Export editor content as a visual preview HTML.
 *
 * This produces a document that visually mimics the editor:
 * - Gray background with white A4 page cards
 * - Content split at page breaks into separate visual pages
 * - Auto-pagination script for overflowing content
 *
 * Used ONLY for the preview iframe — never for PDF generation or copy.
 */
export function exportToPreviewHtml(editorHtml: string, options: ExportOptions = {}): string {
  const {
    title = 'Document',
    pageSize = 'A4',
    margins = { top: '25.4mm', right: '25.4mm', bottom: '25.4mm', left: '25.4mm' },
    extraStyles = '',
    header = '',
    footer = '',
  } = options

  const safeHdr = sanitizeHtml(header)
  const safeFtr = sanitizeHtml(footer)
  const headerHtml = safeHdr ? `<div class="doc-header">${safeHdr}</div>` : ''
  const footerHtml = safeFtr ? `<div class="doc-footer">${safeFtr}</div>` : ''

  const pageSections = splitAtPageBreaks(editorHtml)
  const pagesHtml = pageSections
    .map(section => `<div class="page">${headerHtml}<div class="doc-body">${section}</div>${footerHtml}</div>`)
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.5;
      color: #1a1a1a;
      background: #f0f0f0;
      padding: 32px 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 32px;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .page {
      background: white;
      width: 210mm;
      min-height: 297mm;
      padding: ${margins.top} ${margins.right} ${margins.bottom} ${margins.left};
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1), 0 0 0 1px rgba(0, 0, 0, 0.05);
    }

    @media print {
      body {
        background: white;
        padding: 0;
        display: block;
      }

      @page {
        size: ${pageSize};
        margin: ${margins.top} ${margins.right} ${margins.bottom} ${margins.left};
      }

      .page {
        width: auto;
        min-height: auto;
        padding: 0;
        box-shadow: none;
        page-break-after: always;
      }

      .page:last-child {
        page-break-after: auto;
      }
    }

    ${CONTENT_STYLES}
    ${extraStyles}

    .page-break, div[data-page-break] {
      display: none;
    }

    .page { display: flex; flex-direction: column; overflow: hidden; }
    .doc-body { flex: 1; min-height: 0; }
    .doc-header, .doc-footer {
      font-size: 9pt;
      color: #6b7280;
      padding: 0;
      flex-shrink: 0;
    }
    .doc-header {
      border-bottom: 1px solid #e5e7eb;
      padding: 0 0 4px 0;
      margin: 0 0 8px 0;
      /* Pull header into page padding for edge-to-edge */
      margin-left: -${margins.left};
      margin-right: -${margins.right};
      margin-top: -${margins.top};
      padding: 0;
    }
    .doc-footer {
      border-top: 1px solid #e5e7eb;
      padding: 4px 0 0 0;
      margin: 8px 0 0 0;
      margin-left: -${margins.left};
      margin-right: -${margins.right};
      margin-bottom: -${margins.bottom};
      padding: 0;
    }
    .doc-header img, .doc-footer img { max-width: 100%; height: auto; display: block; }
  </style>
</head>
<body>
  ${pagesHtml}
  <script>
    (function() {
      function paginatePages() {
        var pages = Array.from(document.querySelectorAll('.page'));
        pages.forEach(function(page) {
          var body = page.querySelector('.doc-body');
          if (!body) return;

          var style = getComputedStyle(page);
          var pt = parseFloat(style.paddingTop) || 0;
          var pb = parseFloat(style.paddingBottom) || 0;
          var pageHeight = page.getBoundingClientRect().width * (297 / 210);

          // Account for header/footer heights
          var headerEl = page.querySelector('.doc-header');
          var footerEl = page.querySelector('.doc-footer');
          var headerH = headerEl ? headerEl.getBoundingClientRect().height : 0;
          var footerH = footerEl ? footerEl.getBoundingClientRect().height : 0;
          var maxContent = pageHeight - pt - pb - headerH - footerH;

          if (maxContent <= 0) return;

          var bodyRect = body.getBoundingClientRect();
          if (body.scrollHeight <= maxContent + 2) return;

          var children = Array.from(body.childNodes).filter(function(n) { return n.nodeType === 1; });
          var currentPage = page;
          var currentBody = body;

          children.forEach(function(child) {
            var rect = child.getBoundingClientRect();
            var relTop = rect.top - currentBody.getBoundingClientRect().top;
            var elBottom = relTop + rect.height;

            if (elBottom > maxContent && relTop > 0) {
              // Create new page with header + body + footer
              var newPage = document.createElement('div');
              newPage.className = 'page';
              if (headerEl) newPage.appendChild(headerEl.cloneNode(true));
              var newBody = document.createElement('div');
              newBody.className = 'doc-body';
              newPage.appendChild(newBody);
              if (footerEl) newPage.appendChild(footerEl.cloneNode(true));
              currentPage.parentNode.insertBefore(newPage, currentPage.nextSibling);

              // Move remaining elements to new body
              var sibling = child;
              while (sibling) {
                var next = sibling.nextSibling;
                newBody.appendChild(sibling);
                sibling = next;
              }

              currentPage = newPage;
              currentBody = newBody;
            }
          });
        });
      }

      if (document.readyState === 'complete') {
        setTimeout(paginatePages, 100);
      } else {
        window.addEventListener('load', function() {
          setTimeout(paginatePages, 100);
        });
      }
    })();
  </script>
</body>
</html>`
}

export function exportToHtml(editorHtml: string): string {
  return editorHtml
}

function splitAtPageBreaks(html: string): string[] {
  const pattern = /<div[^>]*(?:data-page-break)[^>]*><\/div>/gi
  const sections = html.split(pattern).filter(s => s.trim().length > 0)
  return sections.length > 0 ? sections : [html]
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Sanitize HTML for safe embedding in exported documents.
 * Strips script tags and event handler attributes to prevent XSS.
 */
function sanitizeHtml(html: string): string {
  if (!html) return html
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
    .replace(/\s*on\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, '')
    .replace(/<iframe\b[^>]*>.*?<\/iframe>/gi, '')
    .replace(/javascript\s*:/gi, '')
}
