import type { Editor } from '@tiptap/react'
import { useEditor } from './use-editor'
import { useBlockStyles } from '../hooks/use-block-styles'
import { EditorToolbar } from '../toolbar/EditorToolbar'
import { BubbleToolbar } from '../toolbar/BubbleToolbar'
import { PageCanvas } from '../canvas/PageCanvas'
import { EditorActions, type EditorActionsConfig } from '../toolbar/EditorActions'
import { exportToPdfHtml, exportToPreviewHtml, hasSmartPageFingerprint } from '../utils/export-html'
import { resolveCanvas } from '../canvas/canvas-config'
import { resolveToolbar } from '../toolbar/toolbar-config'
import { useImperativeHandle, forwardRef, useState, useCallback, useMemo, useRef, useEffect } from 'react'
import type { EditorBlockPlugin } from '../blocks/types'
import type { CanvasConfig, ToolbarConfig, TemplateVariable, ExtensionsConfig, ThemeConfig } from '../types'
import '../editor.css'

export interface SmartPageRef {
  getHTML: () => string
  getPdfHTML: (options?: { title?: string }) => string
  getPreviewHTML: (options?: { title?: string }) => string
  getJSON: () => Record<string, unknown>
  setContent: (html: string) => void
  getVariables: () => TemplateVariable[]
  getHeader: () => string
  getFooter: () => string
  setHeader: (text: string) => void
  setFooter: (text: string) => void
  setReadOnly: (readOnly: boolean) => void
  isReadOnly: () => boolean
  focus: () => void
  clear: () => void
}

export interface SmartPageProps {
  content?: string
  placeholder?: string
  onChange?: (html: string) => void
  className?: string
  variables?: TemplateVariable[] | false
  blocks?: EditorBlockPlugin[]
  header?: string
  footer?: string
  /**
   * Read-only mode. Disables content editing but keeps the document visible.
   * Toolbar remains visible (unless showToolbar={false}) so the user can
   * click the Edit/Preview toggle to switch modes.
   * Can be toggled programmatically via ref.setReadOnly().
   */
  readOnly?: boolean
  /**
   * Whether to show the toolbar. Defaults to true.
   * Set to false to completely hide the toolbar — the user cannot
   * switch between edit/preview modes (true read-only display).
   */
  showToolbar?: boolean
  /**
   * Show a warning banner when loaded content was not generated by SmartPage.
   * Helps users know that externally-created HTML may not render perfectly.
   * Defaults to true.
   */
  warnOnExternalContent?: boolean
  actions?: boolean | EditorActionsConfig
  toolbarActions?: React.ReactNode
  canvas?: 'a4' | 'email' | CanvasConfig
  toolbar?: 'full' | 'minimal' | 'document' | ToolbarConfig
  extensions?: ExtensionsConfig
  theme?: ThemeConfig
}

export const SmartPage = forwardRef<SmartPageRef, SmartPageProps>(
  ({ content, placeholder, onChange, className, variables: initialVariables = false, blocks = [], header: initialHeader = '', footer: initialFooter = '', readOnly: initialReadOnly = false, showToolbar: showToolbarProp, actions = true, toolbarActions, canvas, toolbar, extensions: extensionsProp, theme, warnOnExternalContent = true }, ref) => {
    const variablesEnabled = initialVariables !== false
    const [variables, setVariables] = useState<TemplateVariable[]>(variablesEnabled ? initialVariables : [])
    const [header, setHeader] = useState(initialHeader)
    const [footer, setFooter] = useState(initialFooter)
    const [activeHfEditor, setActiveHfEditor] = useState<Editor | null>(null)
    const [readOnly, setReadOnly] = useState(initialReadOnly)
    const [externalContentWarning, setExternalContentWarning] = useState(false)
    const selfRef = useRef<SmartPageRef | null>(null)

    // Sync prop changes
    useEffect(() => {
      if (initialVariables !== false) setVariables(initialVariables)
    }, [initialVariables])

    useEffect(() => {
      setReadOnly(initialReadOnly)
    }, [initialReadOnly])

    const resolvedCanvas = useMemo(() => resolveCanvas(canvas), [canvas])

    const toolbarFeatures = useMemo(() => {
      const features = resolveToolbar(toolbar)
      if (resolvedCanvas.paginate === false) features.delete('pageBreak')
      if (blocks.length === 0) features.delete('blocks')
      return features
    }, [toolbar, resolvedCanvas.paginate, blocks.length])

    /** Stamp fingerprint on raw HTML output so we can identify SmartPage content later */
    const stampFingerprint = (html: string): string => {
      if (!html || html.trim().length === 0) return html
      // If fingerprint already present, don't duplicate
      if (html.includes('data-smartpage-origin')) return html
      // Insert data-smartpage-origin on the first element
      return html.replace(/^(<\w+)/, '$1 data-smartpage-origin="true"')
    }

    useBlockStyles(blocks)

    const blockExportStyles = useMemo(
      () => blocks.map(b => b.exportStyles || '').filter(Boolean).join('\n'),
      [blocks]
    )

    const editor = useEditor({
      content,
      placeholder,
      variables: variablesEnabled ? variables : false,
      blocks,
      canvas: resolvedCanvas,
      extensions: extensionsProp,
      onUpdate: onChange ? (html: string) => onChange(stampFingerprint(html)) : undefined,
    })

    // Sync editor editable state with readOnly
    useEffect(() => {
      if (editor) {
        editor.setEditable(!readOnly)
      }
    }, [editor, readOnly])

    // Detect external content on initial load — only if content prop has
    // substantial text that lacks the SmartPage fingerprint
    useEffect(() => {
      if (!warnOnExternalContent || !content) return
      if (!hasSmartPageFingerprint(content)) {
        setExternalContentWarning(true)
      }
    }, []) // Only check once on mount

    const handleAddVariable = useCallback((name: string) => {
      setVariables(prev => prev.some(v => v.key === name) ? prev : [...prev, { key: name }])
    }, [])

    const toolbarEditor = activeHfEditor ?? editor

    const refValue: SmartPageRef = {
      getHTML: () => stampFingerprint(editor?.getHTML() ?? ''),
      getPdfHTML: (options) => exportToPdfHtml(editor?.getHTML() ?? '', {
        ...options,
        extraStyles: blockExportStyles,
        header,
        footer,
      }),
      getPreviewHTML: (options) => exportToPreviewHtml(editor?.getHTML() ?? '', {
        ...options,
        extraStyles: blockExportStyles,
        header,
        footer,
      }),
      getJSON: () => editor?.getJSON() as Record<string, unknown> ?? {},
      setContent: (html: string) => {
        if (warnOnExternalContent && html && !hasSmartPageFingerprint(html)) {
          setExternalContentWarning(true)
        } else {
          setExternalContentWarning(false)
        }
        editor?.commands.setContent(html)
      },
      getVariables: () => variables,
      getHeader: () => header,
      getFooter: () => footer,
      setHeader,
      setFooter,
      setReadOnly,
      isReadOnly: () => readOnly,
      focus: () => editor?.commands.focus(),
      clear: () => editor?.commands.clearContent(),
    }

    selfRef.current = refValue
    useImperativeHandle(ref, () => refValue, [editor, variables, blockExportStyles, header, footer, readOnly])

    // Resolve actions config — pass setReadOnly for preview toggle
    const actionsConfig: EditorActionsConfig | null = actions === false
      ? null
      : actions === true
        ? {}
        : actions

    // Build the combined right-side toolbar content
    const rightActions = (
      <>
        {actionsConfig && (
          <EditorActions
            config={actionsConfig}
            editorRef={selfRef}
            readOnly={readOnly}
            onToggleReadOnly={() => setReadOnly(prev => !prev)}
          />
        )}
        {toolbarActions}
      </>
    )

    // Toolbar visible by default — hide only when explicitly set to false
    const showToolbar = showToolbarProp !== false

    if (!editor) return null

    return (
      <div className={`smartpage flex flex-col h-full ${readOnly ? 'smartpage--readonly' : ''} ${className ?? ''}`}>
        {showToolbar && (
          <EditorToolbar
            editor={toolbarEditor}
            variables={variablesEnabled ? variables : undefined}
            onAddVariable={variablesEnabled ? handleAddVariable : undefined}
            blocks={blocks}
            actions={rightActions}
            readOnly={readOnly}
            features={toolbarFeatures}
          />
        )}
        {externalContentWarning && (
          <div className="smartpage-external-warning" style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '8px 16px',
            backgroundColor: '#fef3c7',
            borderBottom: '1px solid #f59e0b',
            fontSize: '13px',
            color: '#92400e',
            lineHeight: 1.4,
          }}>
            <span>This content was not created with SmartPage. Some formatting may not render as expected.</span>
            <button
              onClick={() => setExternalContentWarning(false)}
              style={{
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                padding: '2px 8px',
                fontSize: '13px',
                color: '#92400e',
                fontWeight: 500,
                flexShrink: 0,
                marginLeft: '12px',
              }}
            >
              Dismiss
            </button>
          </div>
        )}
        {showToolbar && !readOnly && resolvedCanvas.paginate && <BubbleToolbar editor={editor} />}
        <PageCanvas
          editor={editor}
          canvas={resolvedCanvas}
          header={header}
          footer={footer}
          onHeaderChange={readOnly ? undefined : setHeader}
          onFooterChange={readOnly ? undefined : setFooter}
          onActiveHfEditor={readOnly ? undefined : setActiveHfEditor}
          readOnly={readOnly}
          theme={theme}
        />
      </div>
    )
  }
)

SmartPage.displayName = 'SmartPage'
